// Code generated by MockGen. DO NOT EDIT.
// Source: src/core/ports/message_port.go

// Package mock_ports is a generated GoMock package.
package mock_ports

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/ronaltrianat/operation-quasar-fire/src/core/domain"
)

// MockMessagePort is a mock of MessagePort interface.
type MockMessagePort struct {
	ctrl     *gomock.Controller
	recorder *MockMessagePortMockRecorder
}

// MockMessagePortMockRecorder is the mock recorder for MockMessagePort.
type MockMessagePortMockRecorder struct {
	mock *MockMessagePort
}

// NewMockMessagePort creates a new mock instance.
func NewMockMessagePort(ctrl *gomock.Controller) *MockMessagePort {
	mock := &MockMessagePort{ctrl: ctrl}
	mock.recorder = &MockMessagePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagePort) EXPECT() *MockMessagePortMockRecorder {
	return m.recorder
}

// CalculateMessage mocks base method.
func (m *MockMessagePort) CalculateMessage(data *domain.SatellitesData) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateMessage", data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateMessage indicates an expected call of CalculateMessage.
func (mr *MockMessagePortMockRecorder) CalculateMessage(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateMessage", reflect.TypeOf((*MockMessagePort)(nil).CalculateMessage), data)
}
